const net = require("net");

const HOST = process.env.HOST || "localhost";
const PORT = process.env.PORT || 3000;

const createConnection = () => {
    const client = net.createConnection({ host: HOST, port: PORT }, () => {
        const buffer = Buffer.alloc(1);
        buffer.writeUInt8(1, 0); // callType 1 for "Stream All Packets"
        client.write(buffer); // I-am-autogenerated
    });
    return client;
};

module.exports = { createConnection };